=== linuslagerhjelm/anti-tower-defence/res/level_schema.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <!-- Rule to restrict int:s to positive numbers -->
    <xsd:simpleType name="PositiveInt">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="0" />
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Describes a rectangle object -->
    <xsd:complexType name="Rectangle">
        <xsd:attribute name="x" type="PositiveInt" use="required" />
        <xsd:attribute name="y" type="PositiveInt" use="required" />
        <xsd:attribute name="width" type="PositiveInt" use="required" />
        <xsd:attribute name="height" type="PositiveInt" use="required" />
    </xsd:complexType>

    <!-- Describes a reference to a node -->
    <xsd:complexType name="Successor">
        <xsd:attribute name="refid" type="xsd:int" use="required" />
    </xsd:complexType>

    <!-- Describes a node which includes references to other nodes-->
    <xsd:complexType name="Node">
        <xsd:sequence>
            <xsd:element name="successor" type="Successor" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required" />
        <xsd:attribute name="x" type="xsd:int" use="required" />
        <xsd:attribute name="y" type="xsd:int" use="required" />
        <xsd:attribute name="start" type="xsd:string" use="optional" />
        <xsd:attribute name="goal" type="xsd:string" use="optional" />
    </xsd:complexType>

    <!-- Describes a directed graph (like structure) of nodes -->
    <xsd:complexType name="Path">
        <xsd:sequence>
            <xsd:element name="node" type="Node" minOccurs="2" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- Describes tower class and amount to be placed -->
    <xsd:complexType name="Tower">
        <xsd:attribute name="className" type="xsd:string" use="required" />
        <xsd:attribute name="count" type="PositiveInt" use="required" />
    </xsd:complexType>

    <!-- Describes what SpecialPad class to load and in which area -->
    <xsd:complexType name="Pad">
        <xsd:sequence>
            <xsd:element name="rectangle" type="Rectangle" minOccurs="1" maxOccurs="1" />
        </xsd:sequence>
        <xsd:attribute name="className" type="xsd:string" use="required" />
    </xsd:complexType>

    <!-- Describes zones where towers are allowed to be placed-->
    <xsd:complexType name="TowerZones">
        <xsd:sequence>
            <xsd:element name="rectangle" type="Rectangle" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- Describes how many and of which types of towers to be placed -->
    <xsd:complexType name="Towers">
        <xsd:sequence>
            <xsd:element name="tower" type="Tower" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- Describes a number of pads to use -->
    <xsd:complexType name="Pads">
        <xsd:sequence>
            <xsd:element name="pad" type="Pad" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- Describes the structure of the xml file -->
    <xsd:complexType name="Level">
        <xsd:all>
            <xsd:element name="path" type="Path" />
            <xsd:element name="towerzones" type="TowerZones" />
            <xsd:element name="towers" type="Towers" />
            <xsd:element name="pads" type="Pads" />
        </xsd:all>

        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="width" type="xsd:int" use="required" />
        <xsd:attribute name="height" type="xsd:int" use="required" />
        <xsd:attribute name="troupesToWin" type="xsd:positiveInteger" use="required" />
        <xsd:attribute name="texture" type="xsd:string" use="required" />
    </xsd:complexType>

    <!-- Defines a list of levels -->
    <xsd:element name="levels">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="level" type="Level" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== linuslagerhjelm/anti-tower-defence/res/level.xml
<?xml version="1.0" encoding="utf-8"?>
<levels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="level_schema.xsd">
    <level name="Level1" width="800" height="600">
        <path>
            <node id="1" x="0" y="0" start="start">
                <successor refid="2" />
                <successor refid="4" />
            </node>
            <node id="2" x="200" y="200">
                <successor refid="3" />
            </node>
            <node id="3" x="100" y="30" goal="goal">
            </node>
            <node id="4" x="30" y="100" goal="goal">
            </node>
        </path>
        <towerzones>
            <rectangle x="3" y="9" width="30" height="40" />
            <rectangle x="30" y="90" width="50" height="80" />
            <rectangle x="60" y="20" width="80" height="80" />
            <rectangle x="200000" y="90000000" width="90" height="50" />
        </towerzones>
        <towers>
            <tower className="SmallTower" count="4" />
            <tower className="LargeTower" count="4" />
        </towers>
        <pads>
            <pad className="TeleportPad">
                <rectangle x="4" y="6" width="3" height="45" />
            </pad>
            <pad className="TeleportPad">
                <rectangle x="6" y="7" width="3" height="45" />
            </pad>
        </pads>
    </level>
</levels>
